<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Citynews/TextToSpeech/TextToSpeec.proto

namespace Services\Citynews;

if (false) {
    /**
     * This class is deprecated. Use Services\Citynews\AudioUnionRequest\BackgroundAudio instead.
     * @deprecated
     */
    class AudioUnionRequest_BackgroundAudio {}
}
class_exists(AudioUnionRequest\BackgroundAudio::class);
@trigger_error('Services\Citynews\AudioUnionRequest_BackgroundAudio is deprecated and will be removed in the next major release. Use Services\Citynews\AudioUnionRequest\BackgroundAudio instead', E_USER_DEPRECATED);

