<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Citynews/TextToSpeech/TextToSpeec.proto

namespace Services\Citynews;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.citynews.HtmlToTextResponse</code>
 */
class HtmlToTextResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.services.shared.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>string text = 2;</code>
     */
    private $text = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Services\Shared\Response $response
     *     @type string $text
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Citynews\TextToSpeech\TextToSpeec::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.services.shared.Response response = 1;</code>
     * @return \Services\Shared\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.services.shared.Response response = 1;</code>
     * @param \Services\Shared\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Services\Shared\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text = 2;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

}

