<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Citynews/Pdf/Pdf.proto

namespace Services\Citynews;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.citynews.PdfFromUrlRequest</code>
 */
class PdfFromUrlRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.services.shared.Request request = 1;</code>
     */
    private $request = null;
    /**
     * Generated from protobuf field <code>string url = 2;</code>
     */
    private $url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Services\Shared\Request $request
     *     @type string $url
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Citynews\Pdf\Pdf::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.services.shared.Request request = 1;</code>
     * @return \Services\Shared\Request
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>.services.shared.Request request = 1;</code>
     * @param \Services\Shared\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Services\Shared\Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 2;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

}

