<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Citynews/TextToSpeech/TextToSpeec.proto

namespace Services\Citynews;

if (false) {
    /**
     * This class is deprecated. Use Services\Citynews\Syntetizator\Syntetize instead.
     * @deprecated
     */
    class Syntetizator_Syntetize {}
}
class_exists(Syntetizator\Syntetize::class);
@trigger_error('Services\Citynews\Syntetizator_Syntetize is deprecated and will be removed in the next major release. Use Services\Citynews\Syntetizator\Syntetize instead', E_USER_DEPRECATED);

