<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Citynews/TextToSpeech/TextToSpeec.proto

namespace Services\Citynews;

if (false) {
    /**
     * This class is deprecated. Use Services\Citynews\Syntetizator\SyntetizeGoogleVoice instead.
     * @deprecated
     */
    class Syntetizator_SyntetizeGoogleVoice {}
}
class_exists(Syntetizator\SyntetizeGoogleVoice::class);
@trigger_error('Services\Citynews\Syntetizator_SyntetizeGoogleVoice is deprecated and will be removed in the next major release. Use Services\Citynews\Syntetizator\SyntetizeGoogleVoice instead', E_USER_DEPRECATED);

