<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Citynews/TextToSpeech/TextToSpeec.proto

namespace Services\Citynews;

if (false) {
    /**
     * This class is deprecated. Use Services\Citynews\Syntetizator\SyntetizeAlexaVoice instead.
     * @deprecated
     */
    class Syntetizator_SyntetizeAlexaVoice {}
}
class_exists(Syntetizator\SyntetizeAlexaVoice::class);
@trigger_error('Services\Citynews\Syntetizator_SyntetizeAlexaVoice is deprecated and will be removed in the next major release. Use Services\Citynews\Syntetizator\SyntetizeAlexaVoice instead', E_USER_DEPRECATED);

