<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Citynews/TextToSpeech/TextToSpeec.proto

namespace Services\Citynews;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.citynews.Syntetizator</code>
 */
class Syntetizator extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.services.citynews.Syntetizator.Syntetize syntetize = 1;</code>
     */
    private $syntetize = 0;
    protected $oneofVoice;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $syntetize
     *     @type int $voiceGoogle
     *     @type int $voiceAlexa
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Citynews\TextToSpeech\TextToSpeec::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.services.citynews.Syntetizator.Syntetize syntetize = 1;</code>
     * @return int
     */
    public function getSyntetize()
    {
        return $this->syntetize;
    }

    /**
     * Generated from protobuf field <code>.services.citynews.Syntetizator.Syntetize syntetize = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSyntetize($var)
    {
        GPBUtil::checkEnum($var, \Services\Citynews\Syntetizator_Syntetize::class);
        $this->syntetize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.services.citynews.Syntetizator.SyntetizeGoogleVoice voiceGoogle = 2;</code>
     * @return int
     */
    public function getVoiceGoogle()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.services.citynews.Syntetizator.SyntetizeGoogleVoice voiceGoogle = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVoiceGoogle($var)
    {
        GPBUtil::checkEnum($var, \Services\Citynews\Syntetizator_SyntetizeGoogleVoice::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.services.citynews.Syntetizator.SyntetizeAlexaVoice voiceAlexa = 3;</code>
     * @return int
     */
    public function getVoiceAlexa()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.services.citynews.Syntetizator.SyntetizeAlexaVoice voiceAlexa = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setVoiceAlexa($var)
    {
        GPBUtil::checkEnum($var, \Services\Citynews\Syntetizator_SyntetizeAlexaVoice::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getOneofVoice()
    {
        return $this->whichOneof("oneofVoice");
    }

}

