<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Citynews/TextToSpeech/TextToSpeec.proto

namespace Services\Citynews;

/**
 * Protobuf type <code>services.citynews.TextToSpeech</code>
 */
interface TextToSpeechInterface
{
    /**
     * Method <code>htmlToText</code>
     *
     * @param \Services\Citynews\HtmlToTextRequest $request
     * @return \Services\Citynews\HtmlToTextResponse
     */
    public function htmlToText(\Services\Citynews\HtmlToTextRequest $request);

    /**
     * Method <code>textToSsml</code>
     *
     * @param \Services\Citynews\TextToSsmlRequest $request
     * @return \Services\Citynews\TextToSsmlResponse
     */
    public function textToSsml(\Services\Citynews\TextToSsmlRequest $request);

    /**
     * Method <code>textToSpeech</code>
     *
     * @param \Services\Citynews\TextToSpeechRequest $request
     * @return \Services\Citynews\TextToSpeechResponse
     */
    public function textToSpeech(\Services\Citynews\TextToSpeechRequest $request);

    /**
     * Method <code>audioUnion</code>
     *
     * @param \Services\Citynews\AudioUnionRequest $request
     * @return \Services\Citynews\AudioUnionResponse
     */
    public function audioUnion(\Services\Citynews\AudioUnionRequest $request);

}

