<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Citynews/TextToSpeech/TextToSpeec.proto

namespace Services\Citynews;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.citynews.TextToSpeechRequest</code>
 */
class TextToSpeechRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.services.shared.Request request = 1;</code>
     */
    private $request = null;
    /**
     * Generated from protobuf field <code>string text = 2;</code>
     */
    private $text = '';
    /**
     * Generated from protobuf field <code>.services.citynews.Syntetizator syntetizator = 3;</code>
     */
    private $syntetizator = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Services\Shared\Request $request
     *     @type string $text
     *     @type \Services\Citynews\Syntetizator $syntetizator
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Citynews\TextToSpeech\TextToSpeec::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.services.shared.Request request = 1;</code>
     * @return \Services\Shared\Request
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>.services.shared.Request request = 1;</code>
     * @param \Services\Shared\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Services\Shared\Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text = 2;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.services.citynews.Syntetizator syntetizator = 3;</code>
     * @return \Services\Citynews\Syntetizator
     */
    public function getSyntetizator()
    {
        return $this->syntetizator;
    }

    /**
     * Generated from protobuf field <code>.services.citynews.Syntetizator syntetizator = 3;</code>
     * @param \Services\Citynews\Syntetizator $var
     * @return $this
     */
    public function setSyntetizator($var)
    {
        GPBUtil::checkMessage($var, \Services\Citynews\Syntetizator::class);
        $this->syntetizator = $var;

        return $this;
    }

}

