<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Citynews/TextToSpeech/TextToSpeec.proto

namespace Services\Citynews\Syntetizator;

use UnexpectedValueException;

/**
 * Protobuf type <code>services.citynews.Syntetizator.SyntetizeAlexaVoice</code>
 */
class SyntetizeAlexaVoice
{
    /**
     * Generated from protobuf enum <code>GIORGIO = 0;</code>
     */
    const GIORGIO = 0;
    /**
     * Generated from protobuf enum <code>CARLA = 1;</code>
     */
    const CARLA = 1;
    /**
     * Generated from protobuf enum <code>BIANCA = 2;</code>
     */
    const BIANCA = 2;

    private static $valueToName = [
        self::GIORGIO => 'GIORGIO',
        self::CARLA => 'CARLA',
        self::BIANCA => 'BIANCA',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SyntetizeAlexaVoice::class, \Services\Citynews\Syntetizator_SyntetizeAlexaVoice::class);

