<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Citynews/TextToSpeech/TextToSpeec.proto

namespace Services\Citynews\AudioUnionRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.citynews.AudioUnionRequest.BackgroundAudio</code>
 */
class BackgroundAudio extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes inputAudio = 1;</code>
     */
    private $inputAudio = '';
    /**
     * Generated from protobuf field <code>int32 volume = 2;</code>
     */
    private $volume = 0;
    /**
     * Generated from protobuf field <code>bool noLoop = 3;</code>
     */
    private $noLoop = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $inputAudio
     *     @type int $volume
     *     @type bool $noLoop
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Citynews\TextToSpeech\TextToSpeec::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes inputAudio = 1;</code>
     * @return string
     */
    public function getInputAudio()
    {
        return $this->inputAudio;
    }

    /**
     * Generated from protobuf field <code>bytes inputAudio = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInputAudio($var)
    {
        GPBUtil::checkString($var, False);
        $this->inputAudio = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 volume = 2;</code>
     * @return int
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Generated from protobuf field <code>int32 volume = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkInt32($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool noLoop = 3;</code>
     * @return bool
     */
    public function getNoLoop()
    {
        return $this->noLoop;
    }

    /**
     * Generated from protobuf field <code>bool noLoop = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoLoop($var)
    {
        GPBUtil::checkBool($var);
        $this->noLoop = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(BackgroundAudio::class, \Services\Citynews\AudioUnionRequest_BackgroundAudio::class);

