<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Shared/Request.proto

namespace GPBMetadata\Shared;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad7010a145368617265642f526571756573742e70726f746f120f736572" .
            "76696365732e73686172656422a5010a0752657175657374122f0a066865" .
            "6164657218012001280b321f2e73657276696365732e7368617265642e52" .
            "6571756573742e486561646572120c0a04626f64791802200128091a5b0a" .
            "06486561646572120f0a0773657276696365180120012809120e0a066d65" .
            "74686f64180220012809120e0a06666f726d6174180320012809120f0a07" .
            "76657273696f6e180420012809120f0a07746f6b656e4964180520012809" .
            "620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

