<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Shared/Response.proto

namespace GPBMetadata\Shared;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7010a155368617265642f526573706f6e73652e70726f746f120f7365" .
            "7276696365732e7368617265642284010a08526573706f6e736512300a06" .
            "68656164657218012001280b32202e73657276696365732e736861726564" .
            "2e526573706f6e73652e486561646572120c0a04626f6479180220012809" .
            "1a380a06486561646572120f0a076d657373616765180120012809120c0a" .
            "04636f6465180220012805120f0a07737563636573731803200128086206" .
            "70726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

