<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Shared/Request.proto

namespace Services\Shared;

if (false) {
    /**
     * This class is deprecated. Use Services\Shared\Request\Header instead.
     * @deprecated
     */
    class Request_Header {}
}
class_exists(Request\Header::class);
@trigger_error('Services\Shared\Request_Header is deprecated and will be removed in the next major release. Use Services\Shared\Request\Header instead', E_USER_DEPRECATED);

