<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Shared/Response.proto

namespace Services\Shared;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.shared.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.services.shared.Response.Header header = 1;</code>
     */
    private $header = null;
    /**
     * Generated from protobuf field <code>string body = 2;</code>
     */
    private $body = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Services\Shared\Response\Header $header
     *     @type string $body
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Shared\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.services.shared.Response.Header header = 1;</code>
     * @return \Services\Shared\Response\Header
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.services.shared.Response.Header header = 1;</code>
     * @param \Services\Shared\Response\Header $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Services\Shared\Response_Header::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string body = 2;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

}

