<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Shared/Response.proto

namespace Services\Shared;

if (false) {
    /**
     * This class is deprecated. Use Services\Shared\Response\Header instead.
     * @deprecated
     */
    class Response_Header {}
}
class_exists(Response\Header::class);
@trigger_error('Services\Shared\Response_Header is deprecated and will be removed in the next major release. Use Services\Shared\Response\Header instead', E_USER_DEPRECATED);

